### ISSUE TITLE
make-cron-job : List args don't works on ECL

### ISSUE THREAD

**Issue by ghost** [ciel-lang/cl-cron#1]
On ECL 21.2.1, Linux Ubuntu 20.04.2 LTS

```
(require :cl-cron)
(defun say-hi () (print "Hi!"))
(cl-cron:make-cron-job #'say-hi :minute '(10 11 13 16))
```
Error :
```
T is not of type LIST.
   [Condition of type TYPE-ERROR]
```

Code above works on SBCL

**Comment by vindarel** [comment]
Thanks for the report. Reproduced on ECL 16.1.2.

(as a reminder, this repository is a fork and not the "official" one on Quicklisp, which was hosted on bitbucket and is currently unavailable. Something must be done about that).
